path: /blog
tag: blog
title: Stoplight API Corner
subtitle: 'Musings on API design, testing, documentation, trends, and related technology.'
color: indigo
tabs:
  - href: /blog
    title: Latest
  - href: /blog/featured
    title: Featured
  - href: /blog/general
    title: General
  - href: /blog/api-design
    title: API Design
  - href: /blog/api-documentation
    title: API Documentation
  - href: /blog/api-testing
    title: API Testing
  - href: /blog/changelog
    title: Changelog
actionBar:
  enabled: true
  text: Sign up for the newsletter
  ctas:
    - title: Sign up for the newsletter
      type: 'submit'
      submit:
        button:
          color: purple
          title: Subscribe
        input:
          type: email
          placeholder: Enter email
        formId: 'e58e3212-f08a-42fe-bbaa-29a21c27a3f5'
meta:
  description: >-
    Find out all you need to know about API design, testing, mocking, and
    documentation from the official Stoplight Blog, written by some of the best
    minds in the business.
  favicon: /images/mark_light_bg.png
  title: Latest Stoplight Blog Posts | Stoplight API Corner
  twitter:
    title: Latest Stoplight Blog Posts | Stoplight API Corner
    username: '@stoplightio'
pagination:
  enabled: true
