path: /open-source/prism
title: Prism - Open Source HTTP Mock Server | Stoplight
color: purple-darker
relatedTags:
  - blog-mocking
hero:
  subtitle: Accelerate API development with realistic mock servers, powered by your OpenAPI documents.
  title: Prism, an Open Source HTTP Mock Server
  particles: true
  ctas:
    - color: green
      href: 'https://github.com/stoplightio/prism'
      title: GitHub
      icon: ['fab', 'github']
    - color: indigo
      href: 'https://youtube.com/watch?v=nZM26knV_ec'
      title: Watch the Video
      icon: ['fad', 'video']
      type: video
    - color: indigo
      href: 'https://stoplight.io/p/docs/gh/stoplightio/prism'
      title: Read the Docs
      icon: ['fad', 'book-open']
featureSection:
  actionBar:
    ctas:
      - href: 'https://stoplight.io/p/docs/gh/stoplightio/prism/docs/getting-started/installation.md'
        title: Get Started with Prism
    enabled: true
    text: Do you want to mock your API in minutes?

  title: Work with your API before you write any code
  description: >-
    Prism is an open source mock server that can mimic your API's behavior as if you already
    built it. Servers are generated from your OpenAPI v2/v3 (formerly known as Swagger) documents.
  features:
    - description: >-
        The waterfall model does not work well for building APIs. Learning at the very end what your
        potential consumers think about your software can be source of huge problems.
        With Prism you can move the feedback stage to the design phase of your API by
        providing a real server to use and play with.
      image: /images/prism_mocking.png
      shortName: Quick Iterations
      title: Quickly iterate on your API

    - description: >-
        Static examples in mock APIs can bias the way you write the code and test the API.
        Prism can generate dynamic random examples based on your API description,
        so the examples are always valid.
      image: /images/prism_dynamic.png
      shortName: Dynamic Examples
      title: Generate dynamic examples

    - description: >-
        Prism validates both request and response data. If you have an
        invalid example in the specification, Prism will let you know; if your request is not compliant with the rules
        of your API specification, Prism will return an error message. It will never yell to you, we promise.
      image: /images/prism_validation.png
      shortName: Validation
      title: Validate input and output

    - description: >-
        In case you're wondering why Prism has responded to a request in such way,
        the logs show you the entire negotiation process, so you can modify the spec
        or your code quickly.
      image: /images/prism_logging.png
      shortName: Logging
      title: Extensive logging
meta:
  description: Accelerate API development with realistic mock servers powered by API descriptions
  favicon: /images/mark_light_bg.png
  image: /images/prism_example.png
  title: Prism - Open Source HTTP Mock Server | Stoplight
  twitter:
    description: Accelerate API development with realistic mock servers powered by API descriptions
    image: /images/prism_example.png
    title: Prism - Open Source HTTP Mock Server | Stoplight
    username: '@stoplightio'
