banners:
  - ends: 1567815331394
    markdown: >-
      Announcing Stoplight Studio, our most powerful API Designer yet, now with OpenAPI v3 support! <u class='ml-1'>**[Learn More](https://stoplight.io/studio)**</u>
    starts: 1565815331394
    hideOnPath: ['/home.', '/studio']
info:
  address:
    addressLocality: Austin
    addressRegion: TX
    alternateName: Stoplight
    description: >-
      Stoplight, providing engineering teams with the best way to document,
      test, and build web APIs.
    email: hello@stoplight.io
    name: Stoplight.io
    postalCode: '78704'
    streetAddress: 1100 S 1st St
  email: sales@stoplight.io
header:
  items:
    - links:
        - href: 'http://docs.stoplight.io/'
          icon: ['fad', 'book-open']
          subtitle: Learn how to use Stoplight
          title: Help Center
          titleColor: blue
        - href: /blog
          icon: ['fad', 'rss']
          subtitle: Stay up to date on Stoplight
          title: Blog
          titleColor: green
        - href: 'https://community.stoplight.io/'
          icon: ['fad', 'users']
          subtitle: Join the Stoplight community
          title: Forum
          titleColor: orange
        - href: /case-studies
          icon: ['fad', 'graduation-cap']
          title: Case Studies
          titleColor: indigo
        - href: /video
          icon: ['fad', 'video']
          subtitle: Learn how to design with Stoplight
          title: Webinars
          titleColor: yellow
        - divider: true
        - href: /api-design-guide/basics
          icon: ['fad', 'paint-brush']
          subtitle: Learn API Design Best Practices
          title: API Design Guide
          titleColor: green
        - href: /mock-api-guide/basics
          icon: ['fad', 'database']
          subtitle: Create mock API servers
          title: API Mocking Guide
          titleColor: blue
        - href: /api-documentation-guide/basics
          icon: ['fad', 'bookmark']
          subtitle: Learn API Documentation Best Practices
          title: API Documentation Guide
          titleColor: purple
      title: Resources
      width: 300
    - href: /enterprise
      title: Enterprise
    - href: /start
      isButton: true
      title: Start
    - href: /demo
      isButton: true
      title: Book a Demo
      altBg: purple
actionBar:
  ctas:
    - color: white
      href: /demo
      title: Book a Demo
      outlined: true
    - color: purple
      href: 'https://stoplight.io/p/signup'
      title: Create a Free Account
  enabled: false
  text: Getting started is easy. Be up and running in minutes.
footer:
  columns:
    - links:
        - href: /studio
          title: Design Studio
        - href: /enterprise
          title: Enterprise Platform
        - href: /hubs
          title: Docs Hubs
      title: Products
    - links:
        - href: /spectral
          title: Spectral
        - href: /prism
          title: Prism
      title: Open Source
    - links:
        - href: 'https://docs.stoplight.io'
          title: Help Center
        - href: /blog
          title: Blog
        - href: 'https://community.stoplight.io'
          title: 'Forum'
        - href: /webinars
          title: Webinars
        - href: /case-studies
          title: Case Studies
      title: Resources
    - links:
        - href: /about
          title: About Us
        - href: https://stoplight.io/p/roadmap
          title: Roadmap
        - href: 'https://press.stoplight.io'
          title: Press
        - href: /contact-us
          title: Contact Us
        - href: 'https://app.stoplight.io/login'
          title: Classic Login
      title: Company
  legal:
    - href: /privacy
      title: Privacy
    - href: /terms
      title: Terms of Use
    - href: /policy
      title: Policy
  social:
    - href: 'https://twitter.com/stoplightio'
      icon: ['fab', 'twitter']
    - href: 'https://www.linkedin.com/company/stoplight'
      icon: ['fab', 'linkedin']
    - href: 'https://www.github.com/stoplightio'
      icon: ['fab', 'github']
meta:
  description: API Design Management for Teams and Enterprise | Stoplight
  favicon: /favicons/favicon.ico
  image: /images/home-hero.png
  robots: 'index, follow'
  title: Stoplight
  twitter:
    description: API Design Management for Teams and Enterprise | Stoplight
    image: /images/home-hero.png
    title: Stoplight
    username: '@stoplightio'
  url: 'https://stoplight.io'
customers:
  images:
    - alt: EA
      src: /images/ea.png
    - alt: Deutsche Bank
      src: /images/deutsche_bank.png
    - alt: quicken
      src: /images/customers/quicken.png
    - alt: Sendgrid
      src: /images/logo-sendgrid.png
    - alt: TiVo
      src: /images/tivo.png
    - alt: Zendesk
      src: /images/logo_zendesk.png
integrations:
  googleTagManager: GTM-58LWL5P
  hubspot: 4892910
  intercom: g7eo4oae
